Repository yunut/kotlin_practice, pull requests merged in 2022-11, with the labels that each got.

#17 review: 회원가입 API 개발
  src/main/kotlin/com/jys/kotlin_practice/account/AccountController.kt
  src/main/kotlin/com/jys/kotlin_practice/account/AccountResponse.kt
  src/main/kotlin/com/jys/kotlin_practice/account/AccountService.kt
  src/main/kotlin/com/jys/kotlin_practice/account/SignupRequest.kt
  src/main/kotlin/com/jys/kotlin_practice/account/error/AccountError.kt
  src/main/kotlin/com/jys/kotlin_practice/account/error/ErrorMessage.kt
  src/main/kotlin/com/jys/kotlin_practice/error/BadRequestErrorCodeException.kt
  src/main/kotlin/com/jys/kotlin_practice/error/Error.kt
  src/test/kotlin/com/jys/kotlin_practice/account/AccountControllerTest.kt
  src/test/kotlin/com/jys/kotlin_practice/account/controller/SignupTest.kt
  src/test/kotlin/com/jys/kotlin_practice/fixture/SignupRequestFixture.kt
Labels: review

#21 회원가입 계정 존재 여부 검증 로직 추가
  build.gradle.kts
  docker-compose.yml
  keycloak/docker/DockerFile
  keycloak/dump/db-backup-17-11-22.sql
  keycloak/dump/db-backup-19-11-22.sql
  keycloak/dump/db-backup-23-11-22.sql
  src/main/kotlin/com/jys/kotlin_practice/account/AccountController.kt
  src/main/kotlin/com/jys/kotlin_practice/account/AccountService.kt
  src/main/kotlin/com/jys/kotlin_practice/account/SignupRequest.kt
  src/main/kotlin/com/jys/kotlin_practice/account/error/AccountError.kt
  src/main/kotlin/com/jys/kotlin_practice/config/KeycloakConfiguration.kt
  src/main/kotlin/com/jys/kotlin_practice/config/SecurityConfiguration.kt
  src/main/kotlin/com/jys/kotlin_practice/error/BadRequestErrorCodeException.kt
  src/main/kotlin/com/jys/kotlin_practice/error/Error.kt
  src/main/kotlin/com/jys/kotlin_practice/keycloak/KeycloakClient.kt
  src/main/kotlin/com/jys/kotlin_practice/keycloak/KeycloakExtension.kt
  src/main/kotlin/com/jys/kotlin_practice/keycloak/KeycloakProperties.kt
  src/main/kotlin/com/jys/kotlin_practice/keycloak/KeycloakRoles.kt
  src/main/resources/application.yml
  src/test/kotlin/com/jys/kotlin_practice/account/controller/SignupTest.kt
  src/test/kotlin/com/jys/kotlin_practice/fixture/SignupRequestFixture.kt
Labels: Review Needed, feature

#27 로그인, 회원가입, 메인페이지 레이아웃 구현
  src/main/kotlin/com/jys/kotlin_practice/account/AccountViewController.kt
  src/main/resources/application.yml
  src/main/resources/static/css/sign.css
  src/main/resources/templates/main.html
  src/main/resources/templates/signin.html
  src/main/resources/templates/signup.html
Labels: feature
